### ISSUE TITLE
Final proofreading

### ISSUE THREAD

**Issue by pneuvial** [computorg/published-202306-sanou-multiscale_glasso#11]
Dear @desanou ,

Here are a couple of final minor points to address to complete the production:

- [x] make figure labels larger. E.g. in [Figure 5](https://computo.sfds.asso.fr/published-202306-sanou-multiscale_glasso/#fig-roc-erdos) the text in x,y and panel labels should have the same size as the main text
- [x] increase line width in Figures 5, 6, 7
- [x] add to figures/ the image files corresponding to the two additional figures discussed during the review process (about scalability and the effect of tolerance), cf https://github.com/computorg/published-202306-sanou-multiscale_glasso/issues/3
- [x] add R code to generate the above figures to scripts/

To address these points, please fork this repository, make the required changes, and submit a pull request to this repository.

**Comment by desanou** [comment]
Dear Editor,

A pull request addressing the issue has been opened. 

The pseudocodes seem to not be compiled in the rendered html and pdf outputs.

Thanks.

**Comment by pneuvial** [comment]
Thanks for  #12, everything is good now.
